### ISSUE TITLE
getIntegrations Exception while running app

### ISSUE THREAD

**Issue by mycaule** [smooch/smooch-desk#35]
```
I20170726-15:01:36.336(2)? Exception while invoking method 'getIntegrations' Error: Bad Request
I20170726-15:01:36.338(2)?     at handleStatus (/Users/michel/Code/Chatbots/smooch-desk/node_modules/smoo
ch-core/lib/utils/http.js:44:17)
I20170726-15:01:36.338(2)?     at /Users/michel/.meteor/packages/promise/.0.8.8.ldfh22++os+web.browser+we
b.cordova/npm/node_modules/meteor-promise/fiber_pool.js:32:39
```

**Comment by ShailChoksi** [comment]
For me this was caused due to having the wrong keys in the settings.json file. Instead of your smooch app's key_id and secret, you need to go to your smooch account and get your key_id and secret from there. This will allow smooch desk the account scope rather than the app scope and then it will be able to get Integrations.

**Comment by alavers** [comment]
I've changed the readme and settings sample a bit to hopefully avoid this issue in the future.
